name       : schedtool
version    : 1.3.0
release    : 1
source     :
    - http://pkgs.fedoraproject.org/repo/pkgs/schedtool/schedtool-1.3.0.tar.bz2/0d968f05d3ad7675f1f33ef1f6d0a3fb/schedtool-1.3.0.tar.bz2 : 4e002a2a619d592f7c9b9d284381ffc004d8a71c38945aa95d5d53f2e4c0c8cf
license    : GPL-2.0
component  : system.utils
summary    : Query or alter a processes scheduling policy
description: |
    Query or alter a processes scheduling policy
build      : |
    %make
install    : |
    %make_install DESTPREFIX=/usr
    rm -r $installdir/usr/share/doc/
